name: Hello World
on:
  workflow_dispatch:
jobs:
  do-things:
    runs-on: [self-hosted, 1ES.Pool=lightning-mcking]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
